POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "name" : "raditya_am",
    "email" : "radityaaqil@gmail.com",
    "password" : "aaaaaaaaA1!"
}

###

POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "radityaaqil@gmail.com",
    "password" : "aaaaaaaaA1!"
}

###

GET http://localhost:5000/auth/keeplogin HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZV9pZCI6MCwiaWF0IjoxNjU1MTExMjcwLCJleHAiOjE2NTUxMzI4NzB9.RJAcy0ZRU6inidXVNa45D8pAkg77yYpaMODFQMmjW08

{

}

###

POST http://localhost:5000/auth/forgotpassword HTTP/1.1
Content-Type: application/json

{
    "email" : "haepram@gmail.com"
}

###

GET http://localhost:5000/auth/verification HTTP/1.1
Authorization: Bearer

{

}

###

POST http://localhost:5000/auth/changepassword HTTP/1.1
Content-Type: application/json
Authorization: Header eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwicm9sZV9pZCI6MCwiaWF0IjoxNjU1Mjk1NDQxLCJleHAiOjE2NTUzMTcwNDF9.GhQ3-rQZBnhtnd_DivyrmPMceotXxbro0ef56sZuGlk 

{
    "oldPassword" : "aaaaaaaaA1!",
    "newPassword" : "aaaaaaaaA5!"
}

###

POST http://localhost:5000/profile/updateusername HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWRpdHlhYXFpbCIsInJvbGVfaWQiOiJ1c2VyIiwiaWF0IjoxNjU1NzA4ODM2LCJleHAiOjE2NTU3MzA0MzZ9.8ZgdGLFHeV5lnjLTHOETfjkyGp_wgAhse2Lu-GYSqsE

{
    "username" : ""
}

###

POST http://localhost:5000/profile/updatephonenumber HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWRpdHlhYXFpbCIsInJvbGVfaWQiOiJ1c2VyIiwiaWF0IjoxNjU1NzA4ODM2LCJleHAiOjE2NTU3MzA0MzZ9.8ZgdGLFHeV5lnjLTHOETfjkyGp_wgAhse2Lu-GYSqsE

{
    "phonenumber" : ""
}

###

POST http://localhost:5000/profile/updatefullname HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWRpdHlhYXFpbCIsInJvbGVfaWQiOiJ1c2VyIiwiaWF0IjoxNjU1NzA4ODM2LCJleHAiOjE2NTU3MzA0MzZ9.8ZgdGLFHeV5lnjLTHOETfjkyGp_wgAhse2Lu-GYSqsE

{
    "fullname" : "Raditya Aqil"
}

###

POST http://localhost:5000/profile/updategender HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWRpdHlhYXFpbCIsInJvbGVfaWQiOiJ1c2VyIiwiaWF0IjoxNjU1NzA4ODM2LCJleHAiOjE2NTU3MzA0MzZ9.8ZgdGLFHeV5lnjLTHOETfjkyGp_wgAhse2Lu-GYSqsE

{
    "gender" : "wanita"
}

###

GET http://localhost:5000/profile/getuserprofile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ0ZXMxMjM0Iiwicm9sZV9pZCI6InVzZXIiLCJpYXQiOjE2NTU3ODEyMzMsImV4cCI6MTY1NTgwMjgzM30.KBdD-5xqjCkrBE5SV2plvsaCbGWBT1tDVSqYvngHG30

{
    
}

###

GET http://localhost:5000/profile/getprovince HTTP/1.1
Content-Type: application/json

{

}

###

GET http://localhost:5000/profile/getcity/12 HTTP/1.1
Content-Type: application/json

{

}

###

POST http://localhost:5000/profile/addaddress HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWRpdHlhYXFpbCIsInJvbGVfaWQiOiJ1c2VyIiwidGltZWNyZWF0ZWQiOjE2NTU5OTMyNjMzODIsImlhdCI6MTY1NTk5MzI2MywiZXhwIjoxNjU2MDE0ODYzfQ.gxW5a6hgwognPABF4k_75p5Tchpf6wNsAn-ss_WFa7Q

{
    "address" : "test1",
    "province" : "test2",
    "city" : "test2",
    "recipient_number" : "test",
    "recipient_name" : "test",
    "address_label" : "test"
}

###

PATCH http://localhost:5000/profile/changedefaultaddress/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJyYWRpdHlhYXFpbCIsInJvbGVfaWQiOiJ1c2VyIiwiaWF0IjoxNjU2MDQ0MjM1LCJleHAiOjE2NTYwNjU4MzV9.A3mFuQNjkb6GWefV56SRUk-nNI2t2U-66PiD94i9UsM

{

}

###

GET http://localhost:5000/profile/getuseraddresses HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6InVzZXIiLCJpYXQiOjE2NTgwNjYxMDEsImV4cCI6MTY1ODE1MjUwMX0.Kv6cQ4WGKXeQo1wAax0qBSyGemqk9uLglDoJfGJ97Ew

{

}

###

GET http://localhost:5000/product/get-category-list HTTP/1.1
Content-Type: application/json

{

}

###

GET http://localhost:5000/product/get-home-product/5 HTTP/1.1
Content-Type: application/json

{

}

###

GET http://localhost:5000/product/get-prescription-product HTTP/1.1
Content-Type: application/json

{
    
}

###

GET http://localhost:5000/transaction/get-transaction-prescription-list?search=tr HTTP/1.1
Content-Type: application/json

{
    
}

###

POST http://localhost:5000/transaction/rejectorder/2 HTTP/1.1
Content-Type: application/json

{
    
}

###

POST http://localhost:5000/transaction/submitprescription/ HTTP/1.1
Content-Type: application/json

{
    
}

###

GET http://localhost:5000/transaction/transaction-detail/13 HTTP/1.1
Content-Type: application/json

{
    
}

###

GET http://localhost:5000/transaction/get-transaction-user-list HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6InVzZXIiLCJpYXQiOjE2NTgwNDMyNjgsImV4cCI6MTY1ODEyOTY2OH0.LtSldW6L22WvMl0w6jka-IXQgE0EjDnMzjkpscXXgD0

{
    
}

###

POST http://localhost:5000/transaction/rejectorder/20 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZV9pZCI6ImFkbWluIiwiaWF0IjoxNjU4MDQyNDkxLCJleHAiOjE2NTgxMjg4OTF9.AzQnm0WVrr7SmqbXynfKS0vL_2fJ6QROn6XxHYF8ZWA

{
    
}

###

GET http://localhost:5000/product/get-products-discount HTTP/1.1
Content-Type: application/json

{

}

###